// <auto-generated />
namespace Web_Store.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UserDateCreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserDateCreated));
        
        string IMigrationMetadata.Id
        {
            get { return "202009221701411_UserDateCreated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
